export const roles = [
  { label: "Company", value: "company" },
  { label: "Operations Manager", value: "opm" },
  { label: "Recruiter", value: "recruiter" },
];

export const rolesAcess = {
  company: [
    {
      id: "1",
      name: "Report Tracker",
      type: "report",
      href: "/dashboard/report-tracker",
      edit: true,
      delete: true,
      view: true,
      create: true,
    },
    {
      id: "2",
      name: "Clients",
      type: "client",
      href: "/dashboard/clients",
      edit: true,
      delete: true,
      view: true,
      create: true,
    },
    {
      id: "3",
      name: "Job Postings",
      type: "job_posting",
      href: "/dashboard/job-postings",
      edit: true,
      delete: true,
      view: true,
      create: true,
    },
    {
      id: "4",
      name: "Candidates",
      href: "/dashboard/candidates",
      type: "candidate",
      edit: true,
      delete: true,
      view: true,
      create: true,
    },
    {
      id: "5",
      name: "Calendar",
      href: "/dashboard/calendar",
      type: "calendar",
      edit: true,
      delete: true,
      view: true,
      create: true,
    },
    {
      id: "6",
      name: "Kanban Boards",
      href: "/dashboard/kanban-boards",
      type: "board",
      edit: true,
      delete: true,
      view: true,
      create: true,
    },
    {
      id: "7",
      name: "Access Control",
      href: "/dashboard/access-control",
      type: "board",
      edit: true,
      delete: true,
      view: true,
      create: true,
    },
  ],
  opm: [
    {
      id: "1",
      name: "Report Tracker",
      type: "report",
      href: "/dashboard/report-tracker",
      edit: true,
      delete: true,
      view: true,
      create: true,
    },
    {
      id: "2",
      name: "Clients",
      type: "client",
      href: "/dashboard/clients",
      edit: true,
      delete: true,
      view: true,
      create: true,
    },
    {
      id: "3",
      name: "Job Postings",
      type: "job_posting",
      href: "/dashboard/job-postings",
      edit: true,
      delete: true,
      view: true,
      create: true,
    },
    {
      id: "4",
      name: "Candidates",
      href: "/dashboard/candidates",
      type: "candidate",
      edit: true,
      delete: true,
      view: true,
      create: true,
    },
    {
      id: "5",
      name: "Calendar",
      href: "/dashboard/calendar",
      type: "calendar",
      edit: true,
      delete: true,
      view: true,
      create: true,
    },
    {
      id: "6",
      name: "Kanban Boards",
      href: "/dashboard/kanban-boards",
      type: "board",
      edit: true,
      delete: true,
      view: true,
      create: true,
    },
    {
      id: "7",
      name: "Access Control",
      href: "/dashboard/access-control",
      type: "board",
      edit: true,
      delete: true,
      view: true,
      create: true,
    },
  ],
  recruiter: [
    {
      id: "1",
      name: "Report Tracker",
      type: "report",
      href: "/dashboard/report-tracker",
      edit: false,
      delete: false,
      view: true,
      create: false,
    },
    {
      id: "2",
      name: "Clients",
      type: "client",
      href: "/dashboard/clients",
      edit: false,
      delete: false,
      view: true,
      create: false,
    },
    {
      id: "3",
      name: "Job Postings",
      type: "job_posting",
      href: "/dashboard/job-postings",
      edit: false,
      delete: false,
      view: true,
      create: false,
    },
    {
      id: "4",
      name: "Candidates",
      href: "/dashboard/candidates",
      type: "candidate",
      edit: true,
      delete: false,
      view: true,
      create: true,
    },
    {
      id: "5",
      name: "Calendar",
      href: "/dashboard/calendar",
      type: "calendar",
      edit: true,
      delete: false,
      view: true,
      create: true,
    },
    {
      id: "6",
      name: "Kanban Boards",
      href: "/dashboard/kanban-boards",
      type: "board",
      edit: true,
      delete: false,
      view: true,
      create: true,
    },
  ],
};

export const pagesAcess = {
  company: [
    { href: "/dashboard", icon: "LayoutGrid", index: 0, label: "Home" },
    {
      href: "/dashboard/report-tracker",
      icon: "BookUp2",
      index: 1,
      label: "Report Tracker",
    },
    {
      href: "/dashboard/clients",
      icon: "Building2",
      index: 2,
      label: "Clients",
    },
    {
      href: "/dashboard/job-postings",
      icon: "ClipboardCheck",
      index: 3,
      label: "Job Postings",
      hasSubmenu: true,
    },
    {
      href: "/dashboard/candidates",
      icon: "Users",
      index: 4,
      label: "Candidates",
    },
    {
      href: "/dashboard/calendar",
      icon: "BarChart3",
      index: 5,
      label: "Calendar",
      hasSubmenu: true,
    },
    {
      href: "/dashboard/kanban-boards",
      icon: "Calendar",
      index: 6,
      label: "Kanban Boards",
    },
    {
      href: "/dashboard/access-control",
      icon: "User2",
      index: 7,
      label: "Access Control",
    },
  ],
  opm: [
    { href: "/dashboard", icon: "LayoutGrid", index: 0, label: "Home" },
    {
      href: "/dashboard/report-tracker",
      icon: "BookUp2",
      index: 1,
      label: "Report Tracker",
    },
    {
      href: "/dashboard/clients",
      icon: "Building2",
      index: 2,
      label: "Clients",
    },
    {
      href: "/dashboard/job-postings",
      icon: "ClipboardCheck",
      index: 3,
      label: "Job Postings",
      hasSubmenu: true,
    },
    {
      href: "/dashboard/candidates",
      icon: "Users",
      index: 4,
      label: "Candidates",
    },
    {
      href: "/dashboard/calendar",
      icon: "BarChart3",
      index: 5,
      label: "Calendar",
      hasSubmenu: true,
    },
    {
      href: "/dashboard/kanban-boards",
      icon: "Calendar",
      index: 6,
      label: "Kanban Boards",
    },
    {
      href: "/dashboard/access-control",
      icon: "User2",
      index: 7,
      label: "Access Control",
    },
  ],
  recruiter: [
    { href: "/dashboard", icon: "LayoutGrid", index: 0, label: "Home" },
    {
      href: "/dashboard/report-tracker",
      icon: "BookUp2",
      index: 1,
      label: "Report Tracker",
    },
    {
      href: "/dashboard/clients",
      icon: "Building2",
      index: 2,
      label: "Clients",
    },
    {
      href: "/dashboard/job-postings",
      icon: "ClipboardCheck",
      index: 3,
      label: "Job Postings",
      hasSubmenu: true,
    },
    {
      href: "/dashboard/candidates",
      icon: "Users",
      index: 4,
      label: "Candidates",
    },
    {
      href: "/dashboard/calendar",
      icon: "BarChart3",
      index: 5,
      label: "Calendar",
      hasSubmenu: true,
    },
    {
      href: "/dashboard/kanban-boards",
      icon: "Calendar",
      index: 6,
      label: "Kanban Boards",
    },
  ],
};
